// ===== v1.9 patch: semantic 128->64->32 multistage renderer =====
(function(){
'use strict';
const VERSION_V19='1.9-semantic-multistage-balance';
function qs9(id){ return typeof qs==='function' ? qs(id) : document.getElementById(id); }
function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }
function fit(c,w,h){ c.width=w; c.height=h; }
function sourceImageData(res){ return res?.pre?.analysis || res?.imgData || state.orig; }
function sourceCanvas(res){ const img=sourceImageData(res); if(!img) throw new Error('source imageData not ready'); const c=document.createElement('canvas'); c.width=img.width; c.height=img.height; c.getContext('2d').putImageData(img,0,0); return c; }
function alphaBBoxFromImageData(img,thr=12){ const w=img.width,h=img.height,d=img.data; let minx=w,miny=h,maxx=-1,maxy=-1; for(let y=0;y<h;y++)for(let x=0;x<w;x++){ const a=d[(y*w+x)*4+3]; if(a>thr){ if(x<minx)minx=x; if(y<miny)miny=y; if(x>maxx)maxx=x; if(y>maxy)maxy=y; } } if(maxx<0) return {minx:0,miny:0,maxx:w-1,maxy:h-1,w,h}; return {minx,miny,maxx,maxy,w:maxx-minx+1,h:maxy-miny+1}; }
function candidateBoxes(res, labels){ return (res?.candidates||[]).filter(r=>labels.includes(r.label)); }
function unionBox(list){ if(!list.length) return null; let minx=1e9,miny=1e9,maxx=-1,maxy=-1; for(const r of list){ const x0=r.minx??0,y0=r.miny??0,x1=r.maxx??(x0+(r.w??0)-1),y1=r.maxy??(y0+(r.h??0)-1); minx=Math.min(minx,x0); miny=Math.min(miny,y0); maxx=Math.max(maxx,x1); maxy=Math.max(maxy,y1); } return {minx,miny,maxx,maxy,w:maxx-minx+1,h:maxy-miny+1}; }
function expandBox(b, imgW, imgH, rx, ry){ if(!b) return null; const padX=Math.round(b.w*rx), padY=Math.round(b.h*ry); const minx=clamp(Math.floor(b.minx-padX),0,imgW-1), miny=clamp(Math.floor(b.miny-padY),0,imgH-1), maxx=clamp(Math.ceil(b.maxx+padX),0,imgH?imgW-1:imgW-1), maxy=clamp(Math.ceil(b.maxy+padY),0,imgH-1); return {minx,miny,maxx,maxy,w:maxx-minx+1,h:maxy-miny+1}; }
function avgColorFromBox(img, box, alphaThr=32){ const w=img.width,h=img.height,d=img.data; let r=0,g=0,b=0,n=0; const x0=clamp(Math.round(box.minx),0,w-1), y0=clamp(Math.round(box.miny),0,h-1), x1=clamp(Math.round(box.maxx),0,w-1), y1=clamp(Math.round(box.maxy),0,h-1); for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){ const i=(y*w+x)*4; if(d[i+3]<alphaThr) continue; r+=d[i]; g+=d[i+1]; b+=d[i+2]; n++; } return n?[Math.round(r/n),Math.round(g/n),Math.round(b/n),255]:[180,180,180,255]; }
function luminance(c){ return 0.299*c[0]+0.587*c[1]+0.114*c[2]; }
function mix(a,b,t){ return [Math.round(a[0]*(1-t)+b[0]*t),Math.round(a[1]*(1-t)+b[1]*t),Math.round(a[2]*(1-t)+b[2]*t),Math.round((a[3]??255)*(1-t)+(b[3]??255)*t)]; }
function dark(c,t=.28){ return mix(c,[28,24,40,255],t); }
function light(c,t=.28){ return mix(c,[255,255,255,255],t); }
function getSemantic(res){
  const img=sourceImageData(res), bb=alphaBBoxFromImageData(img,12), w=img.width, h=img.height;
  const faceCore=unionBox(candidateBoxes(res,['face','eyes','neck']));
  const earCore=unionBox(candidateBoxes(res,['ears']));
  const hairCore=unionBox(candidateBoxes(res,['hair','front_hair','side_hair_left','side_hair_right','back_hair','hair_soft','hair_tip','hair_highlight','hair_shadow']));
  const armCore=unionBox(candidateBoxes(res,['left_arm','right_arm','hands','hand_candidate','sleeve_left','sleeve_right','transparent_cloth','sheer']));
  const legCore=unionBox(candidateBoxes(res,['left_leg','right_leg','legs','leg','shoe','shoes','left_foot','right_foot']));
  const ornamentCore=unionBox(candidateBoxes(res,['ornament','body_ornament','cloth_ornament','necklace','belt','ornament_detail','ornament_candidate']));
  const faceBox=expandBox(faceCore||{minx:bb.minx+bb.w*0.28,miny:bb.miny+bb.h*0.08,maxx:bb.minx+bb.w*0.72,maxy:bb.miny+bb.h*0.34,w:bb.w*0.44,h:bb.h*0.26}, w,h, 0.16,0.12);
  const hairBox=expandBox(hairCore||{minx:bb.minx+bb.w*0.08,miny:bb.miny,maxx:bb.maxx-bb.w*0.08,maxy:bb.miny+bb.h*0.54,w:bb.w*0.84,h:bb.h*0.54}, w,h, 0.05,0.03);
  const bodyTop = clamp(Math.round(faceBox.maxy - bb.h*0.01), bb.miny, bb.maxy);
  const torsoEnd = legCore ? clamp(Math.round(legCore.miny - bb.h*0.02), bodyTop+10, bb.miny+Math.round(bb.h*0.76)) : bb.miny+Math.round(bb.h*0.69);
  const bodyBox = {minx:bb.minx, miny:bodyTop, maxx:bb.maxx, maxy:torsoEnd, w:bb.w, h:torsoEnd-bodyTop+1};
  const legBox = {minx:bb.minx, miny:torsoEnd, maxx:bb.maxx, maxy:bb.maxy, w:bb.w, h:bb.maxy-torsoEnd+1};
  const leftHair = {minx:hairBox.minx, miny:hairBox.miny, maxx:Math.round((hairBox.minx+hairBox.maxx)/2), maxy:hairBox.maxy}; leftHair.w=leftHair.maxx-leftHair.minx+1; leftHair.h=leftHair.maxy-leftHair.miny+1;
  const rightHair = {minx:leftHair.maxx, miny:hairBox.miny, maxx:hairBox.maxx, maxy:hairBox.maxy}; rightHair.w=rightHair.maxx-rightHair.minx+1; rightHair.h=rightHair.maxy-rightHair.miny+1;
  const shoulderWidth = armCore ? clamp(armCore.w/Math.max(1,bb.w),0.35,0.95) : 0.62;
  const hairVolume = hairCore ? clamp(hairCore.w/Math.max(1,bb.w),0.30,0.95) : 0.55;
  const faceColor = avgColorFromBox(img, faceBox, 24);
  const hairColor = avgColorFromBox(img, hairBox, 24);
  const bodyColor = avgColorFromBox(img, bodyBox, 24);
  const ornamentColor = ornamentCore ? avgColorFromBox(img, ornamentCore, 24) : light(bodyColor,.3);
  const eyeColor = luminance(hairColor) < 120 ? light(dark(hairColor,.1),.15) : dark(hairColor,.45);
  const hasEars = !!earCore || (candidateBoxes(res,['ears']).length>0);
  return {bb,faceBox,hairBox,leftHair,rightHair,bodyBox,legBox,shoulderWidth,hairVolume,faceColor,hairColor,bodyColor,ornamentColor,eyeColor,hasEars};
}
function drawCrop(dst, src, box, dx, dy, dw, dh){ if(!box || dw<=0 || dh<=0) return; dst.drawImage(src, box.minx, box.miny, box.w, box.h, dx, dy, dw, dh); }
function drawRoundedFace(ctx, x,y,w,h, skin){ ctx.fillStyle=`rgba(${skin[0]},${skin[1]},${skin[2]},0.98)`; ctx.beginPath(); ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2); ctx.fill(); ctx.fillStyle=`rgba(${light(skin,.18)[0]},${light(skin,.18)[1]},${light(skin,.18)[2]},0.66)`; ctx.beginPath(); ctx.ellipse(x+w/2,y+h*0.42,w*0.33,h*0.20,0,0,Math.PI*2); ctx.fill(); }
function detectEyeCentroidsFromFaceSample(faceSample){ const sctx=faceSample.getContext('2d'); const data=sctx.getImageData(0,0,faceSample.width,faceSample.height).data; let sum=0,n=0; for(let i=0;i<data.length;i+=4){ if(data[i+3]<24) continue; const lum=0.299*data[i]+0.587*data[i+1]+0.114*data[i+2]; sum+=lum; n++; } const avg=n?sum/n:148, thr=avg*0.72; const left=[], right=[]; for(let y=0;y<faceSample.height;y++)for(let x=0;x<faceSample.width;x++){ const i=(y*faceSample.width+x)*4; if(data[i+3]<40) continue; const lum=0.299*data[i]+0.587*data[i+1]+0.114*data[i+2]; if(lum<thr){ if(x<faceSample.width/2) left.push([x,y]); else right.push([x,y]); } } function centroid(arr,fx,fy){ if(!arr.length) return [fx,fy]; let sx=0,sy=0; for(const p of arr){sx+=p[0]; sy+=p[1];} return [sx/arr.length, sy/arr.length]; } return {left:centroid(left,4.5,5.5), right:centroid(right,10.5,5.5)}; }
function makeFaceSample(src, faceBox){ const c=document.createElement('canvas'); fit(c,16,16); const cx=c.getContext('2d'); cx.clearRect(0,0,16,16); cx.imageSmoothingEnabled=true; if(faceBox) cx.drawImage(src, faceBox.minx, faceBox.miny, faceBox.w, faceBox.h, 0,0,16,16); return c; }
function drawFaceFeatures32(ctx, semantic, faceSample){
  const {faceColor, hairColor, eyeColor, hasEars} = semantic;
  const eyes = detectEyeCentroidsFromFaceSample(faceSample);
  // normalize face readability area
  drawRoundedFace(ctx,11,4,10,9,faceColor);
  // ears
  if(hasEars){ ctx.fillStyle=`rgba(${faceColor[0]},${faceColor[1]},${faceColor[2]},0.98)`; ctx.fillRect(9,8,1,2); ctx.fillRect(22,8,1,2); ctx.fillRect(8,9,1,1); ctx.fillRect(23,9,1,1); }
  // bangs / forehead edge
  const hd=dark(hairColor,.18); ctx.fillStyle=`rgba(${hd[0]},${hd[1]},${hd[2]},1)`; ctx.fillRect(10,3,12,2); ctx.fillRect(11,5,10,1); ctx.fillStyle=`rgba(${hairColor[0]},${hairColor[1]},${hairColor[2]},1)`; ctx.fillRect(12,4,8,1);
  // eyes mapped from source sample, but stabilized
  const lx=clamp(Math.round(13 + (eyes.left[0]-4.5)*0.18),12,14); const rx=clamp(Math.round(18 + (eyes.right[0]-10.5)*0.18),17,19); const y=clamp(Math.round(9 + ((eyes.left[1]+eyes.right[1])/2-5.5)*0.12),8,10);
  const ed=dark(eyeColor,.18), eh=light(eyeColor,.45);
  ctx.fillStyle=`rgba(${ed[0]},${ed[1]},${ed[2]},1)`; ctx.fillRect(lx,y,1,2); ctx.fillRect(rx,y,1,2); ctx.fillRect(lx-1,y,1,1); ctx.fillRect(rx+1,y,1,1);
  ctx.fillStyle=`rgba(${eh[0]},${eh[1]},${eh[2]},1)`; ctx.fillRect(lx,y,1,1); ctx.fillRect(rx,y,1,1);
  // blush + mouth
  const blush=light(mix(faceColor,[236,138,170,255],.35),.02); ctx.fillStyle=`rgba(${blush[0]},${blush[1]},${blush[2]},0.92)`; ctx.fillRect(12,12,1,1); ctx.fillRect(19,12,1,1);
  const lip=mix(faceColor,[192,100,120,255],.5); ctx.fillStyle=`rgba(${lip[0]},${lip[1]},${lip[2]},1)`; ctx.fillRect(15,13,2,1);
}
function addOutline(ctx,w,h,alpha=220){ const src=ctx.getImageData(0,0,w,h), out=ctx.getImageData(0,0,w,h), s=src.data,d=out.data; let sr=0,sg=0,sb=0,n=0; for(let i=0;i<s.length;i+=4){ if(s[i+3]>160){sr+=s[i];sg+=s[i+1];sb+=s[i+2];n++;} } const col=n?[Math.max(14,Math.round(sr/n*.26)),Math.max(14,Math.round(sg/n*.26)),Math.max(18,Math.round(sb/n*.30)),alpha]:[44,40,60,alpha]; for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){ const i=(y*w+x)*4; if(s[i+3]) continue; let near=0; for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){ if(!xx&&!yy)continue; if(s[((y+yy)*w+(x+xx))*4+3]>160) near++; } if(near>=2){ d[i]=col[0]; d[i+1]=col[1]; d[i+2]=col[2]; d[i+3]=col[3]; } } ctx.putImageData(out,0,0); }
function palette(ctx,w,h,k){ const d=ctx.getImageData(0,0,w,h).data; const bins=new Map(); for(let i=0;i<d.length;i+=4){ if(d[i+3]<16) continue; const key=((d[i]>>4)<<8)|((d[i+1]>>4)<<4)|(d[i+2]>>4); let o=bins.get(key); if(!o)o={n:0,r:0,g:0,b:0}; o.n++; o.r+=d[i]; o.g+=d[i+1]; o.b+=d[i+2]; bins.set(key,o);} const arr=[...bins.values()].sort((a,b)=>b.n-a.n).slice(0,k); return arr.length?arr.map(o=>[Math.round(o.r/o.n),Math.round(o.g/o.n),Math.round(o.b/o.n),255]):[[0,0,0,0]]; }
function nearest(c,pal){ let best=pal[0], bd=1e18; for(const p of pal){ const dr=c[0]-p[0], dg=c[1]-p[1], db=c[2]-p[2]; const dd=dr*dr+dg*dg+db*db; if(dd<bd){ bd=dd; best=p; } } return best; }
function quantize(ctx,w,h,k){ const img=ctx.getImageData(0,0,w,h), d=img.data, pal=palette(ctx,w,h,k); for(let i=0;i<d.length;i+=4){ if(d[i+3]<20){ d[i]=d[i+1]=d[i+2]=d[i+3]=0; continue; } const p=nearest([d[i],d[i+1],d[i+2]],pal); d[i]=p[0]; d[i+1]=p[1]; d[i+2]=p[2]; d[i+3]=255; } ctx.putImageData(img,0,0); return pal; }
function composeStage128(res, semantic){
  const src=sourceCanvas(res); const c=document.createElement('canvas'); fit(c,128,128); const ctx=c.getContext('2d'); ctx.clearRect(0,0,128,128); ctx.imageSmoothingEnabled=true;
  // body first so hair can sit around it
  const bodyW=Math.round(48 + semantic.shoulderWidth*18), bodyX=Math.round((128-bodyW)/2); drawCrop(ctx, src, semantic.bodyBox, bodyX, 52, bodyW, 32);
  drawCrop(ctx, src, semantic.legBox, 47, 82, 34, 40);
  // hair silhouette mass / side hair
  const hairW=Math.round(82 + semantic.hairVolume*12), hairX=Math.round((128-hairW)/2); drawCrop(ctx, src, semantic.hairBox, hairX, 2, hairW, 62);
  drawCrop(ctx, src, semantic.leftHair, 4, 18, 28, 78);
  drawCrop(ctx, src, semantic.rightHair, 96, 18, 28, 78);
  // face clear and enlarged re-placement
  ctx.clearRect(34, 10, 60, 38); drawCrop(ctx, src, semantic.faceBox, 38, 12, 52, 32);
  // bangs / front hair strip on top of face to restore hairstyle
  const frontHair={minx:Math.round((semantic.hairBox.minx+semantic.faceBox.minx)/2), miny:semantic.hairBox.miny, maxx:Math.round((semantic.hairBox.maxx+semantic.faceBox.maxx)/2), maxy:Math.min(semantic.hairBox.maxy, semantic.faceBox.miny + semantic.faceBox.h*0.55)}; frontHair.w=frontHair.maxx-frontHair.minx+1; frontHair.h=frontHair.maxy-frontHair.miny+1;
  drawCrop(ctx, src, frontHair, 36, 4, 56, 24);
  // ornaments representative points
  ctx.fillStyle=`rgba(${semantic.ornamentColor[0]},${semantic.ornamentColor[1]},${semantic.ornamentColor[2]},0.92)`; ctx.fillRect(61,49,6,4); ctx.fillRect(56,59,2,2); ctx.fillRect(70,59,2,2);
  return c;
}
function stage128To64(stage128, semantic){ const c=document.createElement('canvas'); fit(c,64,64); const ctx=c.getContext('2d'); ctx.clearRect(0,0,64,64); ctx.imageSmoothingEnabled=true; ctx.drawImage(stage128,0,0,64,64); quantize(ctx,64,64, clamp(parseInt(qs9('k')?.value||'8',10)+4,6,16)); addOutline(ctx,64,64,180); // subtle face recovery already at 64
  const faceSample=makeFaceSample(sourceCanvas(state.result), semantic.faceBox); const tmp=document.createElement('canvas'); fit(tmp,32,32); tmp.getContext('2d').drawImage(c,0,0,32,32); drawFaceFeatures32(tmp.getContext('2d'), semantic, faceSample); ctx.clearRect(0,0,64,64); ctx.imageSmoothingEnabled=false; ctx.drawImage(tmp,0,0,64,64); return c; }
function stage64To32(stage64, semantic){ const c=document.createElement('canvas'); fit(c,32,32); const ctx=c.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.imageSmoothingEnabled=true; ctx.drawImage(stage64,0,0,32,32); quantize(ctx,32,32, clamp(parseInt(qs9('k')?.value||'8',10)+1,5,14)); addOutline(ctx,32,32,220); drawFaceFeatures32(ctx, semantic, makeFaceSample(sourceCanvas(state.result), semantic.faceBox)); return c; }
function renderBalanced3Stage(res){ const semantic=getSemantic(res); const s128=composeStage128(res, semantic); const s64=stage128To64(s128, semantic); const s32=stage64To32(s64, semantic); return {stage128:s128, stage64:s64, canvas:s32, semantic, mode:'balanced_3stage'}; }
function renderFaithful(res){ const src=sourceCanvas(res), bb=alphaBBoxFromImageData(sourceImageData(res),12); const out=document.createElement('canvas'); fit(out,32,32); const ctx=out.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.imageSmoothingEnabled=true; const targetH=30, scale=targetH/Math.max(1,bb.h), dw=Math.max(1,Math.round(bb.w*scale)), dx=Math.round((32-dw)/2), dy=1; ctx.drawImage(src,bb.minx,bb.miny,bb.w,bb.h,dx,dy,dw,targetH); const pal=quantize(ctx,32,32, clamp(parseInt(qs9('k')?.value||'8',10)+1,5,14)); addOutline(ctx,32,32,220); return {canvas:out, mode:'faithful', semantic:{bb,scale,offset:{x:dx,y:dy}}, paletteSize:pal.length}; }
function renderV19(res){ const mode=(qs9('pixelMode')?.value || 'balanced_3stage'); return mode==='faithful' ? renderFaithful(res) : renderBalanced3Stage(res); }
function applyResult(res, pack){ const id=pack.canvas.getContext('2d').getImageData(0,0,32,32); const semantic=pack.semantic||{}; const payload={imageData:id,status:'ok',renderer:'semantic_multistage_v1_9',mode:pack.mode,semantic:{bb:semantic.bb||null,faceBox:semantic.faceBox||null,hairBox:semantic.hairBox||null,bodyBox:semantic.bodyBox||null,legBox:semantic.legBox||null,hairVolume:semantic.hairVolume||null,shoulderWidth:semantic.shoulderWidth||null},note:'128->64->32 multi-stage semantic pipeline with face protection, eye redraw, and hair silhouette preservation'}; res.sprite32V19=payload; res.sprite32V18=payload; res.sprite32V17=payload; res.sprite32V16=payload; res.sprite32V15=payload; res.sprite32V14=payload; res.sprite32V13=payload; res.sprite32V12=payload; res.sprite32V11=payload; res.sprite32V10=res.sprite32V10||{}; res.sprite32V10.imageData=id; res.sprite32V10.status='ok-v1.9'; return id; }
function saveLink(dataUrl,name,label){ try{ const a=document.createElement('a'); a.href=dataUrl; a.download=name; document.body.appendChild(a); a.click(); setTimeout(()=>a.remove(),400); }catch(e){} const log=qs9('pixelLog')||qs9('log'); if(log){ let box=document.getElementById('saveLinksV19'); if(!box){ box=document.createElement('div'); box.id='saveLinksV19'; box.style.marginTop='10px'; log.parentNode.appendChild(box); } const a=document.createElement('a'); a.href=dataUrl; a.download=name; a.target='_blank'; a.rel='noopener'; a.textContent=label||name; a.style.display='inline-block'; a.style.margin='6px 8px 0 0'; a.style.padding='8px 10px'; a.style.border='1px solid #58a6ff'; a.style.borderRadius='10px'; a.style.color='#58a6ff'; box.prepend(a); } }
function saveSprite32V19(){ if(!state.result){ alert('先に解析してください。'); return; } const pack=renderV19(state.result); saveLink(pack.canvas.toDataURL('image/png'), `sprite_front_32_v1_9_${pack.mode}.png`, `画像を開く/保存 sprite_front_32_v1_9_${pack.mode}.png`); }
function projectV19(){ const res=state.result; if(!res) return {version:VERSION_V19,status:'no_result'}; if(!res.sprite32V19){ const pack=renderV19(res); applyResult(res,pack); } return {version:VERSION_V19,type:'game_sprite_32_semantic_multistage',output:{sprite:`sprite_front_32_v1_9_${res.sprite32V19.mode}.png`,size:{w:32,h:32}},renderer:'semantic_multistage_v1_9',mode:res.sprite32V19.mode,semantic:res.sprite32V19.semantic,goal:'balance cute readability and source fidelity using 128->64->32 reconstruction stages'}; }
function saveProjectV19(){ if(!state.result){ alert('先に解析してください。'); return; } saveLink('data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(projectV19(),null,2)), `sprite_pixel_project_v1_9_${qs9('pixelMode')?.value||'balanced_3stage'}.json`, `JSONを開く/保存 sprite_pixel_project_v1_9_${qs9('pixelMode')?.value||'balanced_3stage'}.json`); }
function drawV19(){ if(!state.result) return; const pack=renderV19(state.result); const id=applyResult(state.result,pack); const c32=qs9('cSprite32'), prev=qs9('cSpritePreview'), st=qs9('spriteStatus'), log=qs9('pixelLog'); if(c32){ fit(c32,32,32); const ctx=c32.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.putImageData(id,0,0); } if(prev){ fit(prev,320,320); const ctx=prev.getContext('2d'); ctx.imageSmoothingEnabled=false; ctx.fillStyle='#0b111b'; ctx.fillRect(0,0,320,320); ctx.strokeStyle='rgba(255,255,255,.08)'; for(let i=0;i<=32;i++){ ctx.beginPath(); ctx.moveTo(i*10,0); ctx.lineTo(i*10,320); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0,i*10); ctx.lineTo(320,i*10); ctx.stroke(); } const t=document.createElement('canvas'); t.width=32; t.height=32; t.getContext('2d').putImageData(id,0,0); ctx.drawImage(t,0,0,320,320); } if(st) st.textContent=`v1.9 ${pack.mode}`; if(log){ const s=pack.semantic||{}; log.textContent=`Sprite v1.9\nstatus=ok\nrenderer=semantic_multistage_v1_9\nmode=${pack.mode}\n\n3段階パイプライン:\n- stage1 = 128x128 semantic reconstruct\n- stage2 = 64x64 simplify\n- stage3 = 32x32 final sprite\n\n保護内容:\n- 顔 = 独立保護 + 拡大再配置\n- 目 = source face sample を使って再描画\n- 髪 = 左右サイド髪 + 前髪ストリップを保持\n- 胴体/脚 = true-source から再配置\n\nsemantic:\n- bbox = ${s.bb?`${s.bb.w}x${s.bb.h}`:'-'}\n- hairVolume = ${typeof s.hairVolume==='number' ? s.hairVolume.toFixed(2) : '-'}\n- shoulderWidth = ${typeof s.shoulderWidth==='number' ? s.shoulderWidth.toFixed(2) : '-'}\n\n狙い:\n- v1.7よりデフォルメ\n- v1.8より顔が読める\n- true-source の髪/服の個性を残す`; } }
function addModeUi(){ const bar=document.querySelector('.bar'); if(!bar) return; let sel=qs9('pixelMode'); if(!sel){ sel=document.createElement('select'); sel.id='pixelMode'; const run=qs9('run'); if(run) bar.insertBefore(sel,run); else bar.appendChild(sel); } sel.innerHTML='<option value="balanced_3stage">ドット化:Cバランス 128→64→32</option><option value="faithful">ドット化:元画像忠実</option>'; if(!sel.value || sel.value==='hybrid_chibi') sel.value='balanced_3stage'; sel.onchange=()=>{ if(state.result) drawV19(); }; }
function installV19(){ addModeUi(); const b1=qs9('saveSprite32'); if(b1) b1.onclick=saveSprite32V19; const b2=qs9('savePixelProject'); if(b2) b2.onclick=saveProjectV19; const oldAnalyze=(typeof analyze==='function') ? analyze : null; async function analyzeV19(){ if(oldAnalyze) await oldAnalyze(); try{ if(state.result) drawV19(); }catch(e){ console.warn('v1.9 draw failed',e); } } analyze=analyzeV19; window.analyzeV19=analyzeV19; window.renderSemanticSpriteV19=renderV19; const run=qs9('run'); if(run) run.onclick=analyzeV19; ['adjFace','adjShoulder','adjWaist','adjCrotch','adjAnkle'].forEach(id=>{ const el=qs9(id); if(el) el.oninput=()=>{ state.lineAdjust={face:+(qs9('adjFace')?.value||0),shoulder:+(qs9('adjShoulder')?.value||0),waist:+(qs9('adjWaist')?.value||0),crotch:+(qs9('adjCrotch')?.value||0),ankle:+(qs9('adjAnkle')?.value||0)}; analyzeV19(); }; }); document.title='Sprite Studio Pixel Pipeline v1.9'; const h1=document.querySelector('h1'); if(h1) h1.textContent='Sprite Studio Pixel Pipeline v1.9'; const sub=document.querySelector('.sub'); if(sub) sub.textContent='AIなし / Canvas + localStorageのみ。v1.9: semantic multi-stage balance。128→64→32で顔保護・目再描画・髪外形保持まで行います。'; const footer=document.querySelector('.footer'); if(footer) footer.textContent='v1.9は semantic multi-stage balance renderer です。C方針で、true-sourceを維持しながら128→64→32の各段階で再構成を行います。'; }
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',installV19); else installV19();
if(typeof metadata092==='function'){ const oldMeta=metadata092; metadata092=function(){ const m=oldMeta(); m.version=VERSION_V19; m.pixel_sprite_v19={status:state.result?.sprite32V19?.status||'not_run',renderer:'semantic_multistage_v1_9',mode:state.result?.sprite32V19?.mode||null,semantic:state.result?.sprite32V19?.semantic||null}; return m; }; }
})();
