// ===== v1.10 patch: mask-part semantic renderer =====
(function(){
'use strict';
const VERSION='1.10-mask-part-semantic';
function qs10(id){ return typeof qs==='function' ? qs(id) : document.getElementById(id); }
function fit(c,w,h){ c.width=w; c.height=h; }
function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }
function srcImg(res){ return res?.pre?.analysis || res?.imgData || state.orig; }
function groupPixels(cands, labels){ const set=new Set(labels); const out=[]; for(const r of (cands||[])){ if(set.has(r.label)) out.push(r); } return out; }
function partFromLabels(img, cands, labels, pad=2){ const picks=groupPixels(cands, labels); if(!picks.length) return null; const w=img.width,h=img.height,d=img.data; let minx=w,miny=h,maxx=-1,maxy=-1; const mask=new Uint8Array(w*h); for(const r of picks){ for(const p of (r.pixels||[])){ mask[p]=1; const x=p%w, y=(p/w)|0; if(x<minx)minx=x; if(y<miny)miny=y; if(x>maxx)maxx=x; if(y>maxy)maxy=y; } }
 if(maxx<0) return null; minx=clamp(minx-pad,0,w-1); miny=clamp(miny-pad,0,h-1); maxx=clamp(maxx+pad,0,w-1); maxy=clamp(maxy+pad,0,h-1); const pw=maxx-minx+1, ph=maxy-miny+1; const c=document.createElement('canvas'); fit(c,pw,ph); const ctx=c.getContext('2d'); const out=ctx.createImageData(pw,ph); for(let y=miny;y<=maxy;y++)for(let x=minx;x<=maxx;x++){ const p=y*w+x; if(!mask[p]) continue; const si=p*4, di=((y-miny)*pw + (x-minx))*4; out.data[di]=d[si]; out.data[di+1]=d[si+1]; out.data[di+2]=d[si+2]; out.data[di+3]=d[si+3]; } ctx.putImageData(out,0,0); return {canvas:c,bbox:{minx,miny,maxx,maxy,w:pw,h:ph},count:picks.length,labels}; }
function detectParts(res){ const img=srcImg(res), cands=res?.candidates||[]; return {
   hair: partFromLabels(img,cands,['hair','front_hair','side_hair_left','side_hair_right','back_hair','hair_soft','hair_tip','soft_shell'],3),
   face: partFromLabels(img,cands,['face'],2),
   neck: partFromLabels(img,cands,['neck'],1),
   ears: partFromLabels(img,cands,['ears'],1),
   eyes: partFromLabels(img,cands,['eyes','eye_candidate'],1),
   body: partFromLabels(img,cands,['upper_cloth','lower_cloth','cloth_detail','collar'],2),
   sleeves: partFromLabels(img,cands,['transparent_cloth'],2),
   hands: partFromLabels(img,cands,['hands','hand_candidate'],1),
   legs: partFromLabels(img,cands,['left_leg','right_leg','leg','legs'],2),
   shoes: partFromLabels(img,cands,['shoe','shoes'],1),
   ornaments: partFromLabels(img,cands,['cloth_ornament','ornament_detail'],1)
 };
}
function avgColorCanvas(c){ if(!c) return [180,180,180,255]; const ctx=c.getContext('2d'), {data}=ctx.getImageData(0,0,c.width,c.height); let r=0,g=0,b=0,n=0; for(let i=0;i<data.length;i+=4){ if(data[i+3]<24) continue; r+=data[i]; g+=data[i+1]; b+=data[i+2]; n++; } return n?[Math.round(r/n),Math.round(g/n),Math.round(b/n),255]:[180,180,180,255]; }
function mix(a,b,t){ return [Math.round(a[0]*(1-t)+b[0]*t),Math.round(a[1]*(1-t)+b[1]*t),Math.round(a[2]*(1-t)+b[2]*t),255]; }
function dark(c,t=.3){ return mix(c,[24,22,36,255],t); }
function light(c,t=.25){ return mix(c,[255,255,255,255],t); }
function drawScaled(ctx, part, dx, dy, dw, dh){ if(!part||!part.canvas||dw<=0||dh<=0) return; ctx.drawImage(part.canvas,0,0,part.canvas.width,part.canvas.height,dx,dy,dw,dh); }
function drawMirrorHalf(ctx, part, leftDx,leftDy,leftW,leftH,rightDx,rightDy,rightW,rightH){ if(!part) return; const half=Math.max(1,Math.floor(part.canvas.width/2)); ctx.drawImage(part.canvas,0,0,half,part.canvas.height,leftDx,leftDy,leftW,leftH); ctx.drawImage(part.canvas,part.canvas.width-half,0,half,part.canvas.height,rightDx,rightDy,rightW,rightH); }
function drawFaceReadability(ctx, parts){ const faceC=avgColorCanvas(parts.face?.canvas); const hairC=avgColorCanvas(parts.hair?.canvas); const eyeBase=parts.eyes ? avgColorCanvas(parts.eyes.canvas) : dark(hairC,.45); const blush=mix(faceC,[236,138,170,255],.35); const lx=13, rx=18, y=9; const fringe=dark(hairC,.12); ctx.fillStyle=`rgba(${fringe[0]},${fringe[1]},${fringe[2]},1)`; ctx.fillRect(10,4,12,2); ctx.fillRect(12,6,8,1); const ed=dark(eyeBase,.15), eh=light(eyeBase,.48); ctx.fillStyle=`rgba(${ed[0]},${ed[1]},${ed[2]},1)`; ctx.fillRect(lx,y,1,2); ctx.fillRect(rx,y,1,2); ctx.fillRect(lx-1,y,1,1); ctx.fillRect(rx+1,y,1,1); ctx.fillStyle=`rgba(${eh[0]},${eh[1]},${eh[2]},1)`; ctx.fillRect(lx,y,1,1); ctx.fillRect(rx,y,1,1); ctx.fillStyle=`rgba(${blush[0]},${blush[1]},${blush[2]},0.95)`; ctx.fillRect(12,12,1,1); ctx.fillRect(19,12,1,1); const lip=mix(faceC,[192,100,120,255],.52); ctx.fillStyle=`rgba(${lip[0]},${lip[1]},${lip[2]},1)`; ctx.fillRect(15,13,2,1); }
function addOutline(ctx,w,h,alpha=220){ const src=ctx.getImageData(0,0,w,h), out=ctx.getImageData(0,0,w,h), s=src.data,d=out.data; let sr=0,sg=0,sb=0,n=0; for(let i=0;i<s.length;i+=4){ if(s[i+3]>160){ sr+=s[i]; sg+=s[i+1]; sb+=s[i+2]; n++; } } const col=n?[Math.max(12,Math.round(sr/n*.24)),Math.max(12,Math.round(sg/n*.24)),Math.max(18,Math.round(sb/n*.28)),alpha]:[42,38,56,alpha]; for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){ const i=(y*w+x)*4; if(s[i+3]) continue; let near=0; for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){ if(!xx&&!yy) continue; if(s[((y+yy)*w+(x+xx))*4+3]>160) near++; } if(near>=2){ d[i]=col[0]; d[i+1]=col[1]; d[i+2]=col[2]; d[i+3]=col[3]; } } ctx.putImageData(out,0,0); }
function palette(ctx,w,h,k){ const d=ctx.getImageData(0,0,w,h).data; const bins=new Map(); for(let i=0;i<d.length;i+=4){ if(d[i+3]<16) continue; const key=((d[i]>>4)<<8)|((d[i+1]>>4)<<4)|(d[i+2]>>4); let o=bins.get(key); if(!o)o={n:0,r:0,g:0,b:0}; o.n++; o.r+=d[i]; o.g+=d[i+1]; o.b+=d[i+2]; bins.set(key,o); } const arr=[...bins.values()].sort((a,b)=>b.n-a.n).slice(0,k); return arr.length?arr.map(o=>[Math.round(o.r/o.n),Math.round(o.g/o.n),Math.round(o.b/o.n),255]):[[0,0,0,0]]; }
function nearest(c,pal){ let best=pal[0],bd=1e18; for(const p of pal){ const dr=c[0]-p[0],dg=c[1]-p[1],db=c[2]-p[2]; const dd=dr*dr+dg*dg+db*db; if(dd<bd){ bd=dd; best=p; } } return best; }
function quantize(ctx,w,h,k){ const img=ctx.getImageData(0,0,w,h), d=img.data, pal=palette(ctx,w,h,k); for(let i=0;i<d.length;i+=4){ if(d[i+3]<20){ d[i]=d[i+1]=d[i+2]=d[i+3]=0; continue; } const p=nearest([d[i],d[i+1],d[i+2]],pal); d[i]=p[0]; d[i+1]=p[1]; d[i+2]=p[2]; d[i+3]=255; } ctx.putImageData(img,0,0); return pal; }
function compose128(parts){ const c=document.createElement('canvas'); fit(c,128,128); const ctx=c.getContext('2d'); ctx.clearRect(0,0,128,128); ctx.imageSmoothingEnabled=true;
  drawScaled(ctx, parts.hair, 22, 2, 84, 70);
  if(parts.sleeves){ drawMirrorHalf(ctx, parts.sleeves, 8, 45, 20, 54, 100, 45, 20, 54); }
  drawScaled(ctx, parts.body, 42, 53, 44, 34);
  if(parts.ornaments) drawScaled(ctx, parts.ornaments, 48, 54, 32, 18);
  drawScaled(ctx, parts.legs, 48, 84, 32, 30);
  drawScaled(ctx, parts.shoes, 49, 113, 30, 11);
  drawScaled(ctx, parts.face, 44, 15, 40, 26);
  drawScaled(ctx, parts.ears, 36, 18, 56, 18);
  drawScaled(ctx, parts.neck, 54, 42, 20, 9);
  if(parts.hair){
    const hw=parts.hair.canvas.width, hh=parts.hair.canvas.height;
    ctx.drawImage(parts.hair.canvas, Math.floor(hw*0.18), 0, Math.max(1,Math.floor(hw*0.64)), Math.max(1,Math.floor(hh*0.32)), 38, 4, 52, 22);
    ctx.drawImage(parts.hair.canvas, 0, 0, Math.max(1,Math.floor(hw*0.28)), hh, 12, 18, 18, 66);
    ctx.drawImage(parts.hair.canvas, Math.floor(hw*0.72), 0, Math.max(1,Math.floor(hw*0.28)), hh, 98, 18, 18, 66);
  }
  if(parts.hands){ drawMirrorHalf(ctx, parts.hands, 29, 69, 10, 16, 89, 69, 10, 16); }
  drawScaled(ctx, parts.eyes, 51, 24, 26, 8);
  return c; }
function compose64(stage128){ const c=document.createElement('canvas'); fit(c,64,64); const ctx=c.getContext('2d'); ctx.clearRect(0,0,64,64); ctx.imageSmoothingEnabled=true; ctx.drawImage(stage128,0,0,64,64); quantize(ctx,64,64, clamp(parseInt(qs10('k')?.value||'8',10)+2,6,14)); addOutline(ctx,64,64,180); return c; }
function compose32(stage64, parts){ const c=document.createElement('canvas'); fit(c,32,32); const ctx=c.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.imageSmoothingEnabled=true; ctx.drawImage(stage64,0,0,32,32); quantize(ctx,32,32, clamp(parseInt(qs10('k')?.value||'8',10)+1,5,12)); addOutline(ctx,32,32,220); drawFaceReadability(ctx, parts); return c; }
function renderV110(res){ const parts=detectParts(res); const stage128=compose128(parts); const stage64=compose64(stage128); const out=compose32(stage64, parts); return {canvas:out, stage128, stage64, parts, mode:'mask_part_semantic'}; }
function applyResult(res, pack){ const id=pack.canvas.getContext('2d').getImageData(0,0,32,32); const partSummary={}; for(const [k,v] of Object.entries(pack.parts||{})){ if(v) partSummary[k]={w:v.canvas.width,h:v.canvas.height,count:v.count,labels:v.labels}; } const payload={imageData:id,status:'ok',renderer:'mask_part_semantic_v1_10',mode:pack.mode,parts:partSummary,note:'uses candidate pixel masks instead of rectangular source crops'}; res.sprite32V110=payload; res.sprite32V19=payload; res.sprite32V18=payload; res.sprite32V17=payload; res.sprite32V16=payload; res.sprite32V15=payload; res.sprite32V14=payload; res.sprite32V13=payload; res.sprite32V12=payload; res.sprite32V11=payload; res.sprite32V10=res.sprite32V10||{}; res.sprite32V10.imageData=id; res.sprite32V10.status='ok-v1.10'; return id; }
function saveLink(dataUrl,name,label){ try{ const a=document.createElement('a'); a.href=dataUrl; a.download=name; document.body.appendChild(a); a.click(); setTimeout(()=>a.remove(),400); }catch(e){} const log=qs10('pixelLog')||qs10('log'); if(log){ let box=document.getElementById('saveLinksV110'); if(!box){ box=document.createElement('div'); box.id='saveLinksV110'; box.style.marginTop='10px'; log.parentNode.appendChild(box); } const a=document.createElement('a'); a.href=dataUrl; a.download=name; a.target='_blank'; a.rel='noopener'; a.textContent=label||name; a.style.display='inline-block'; a.style.margin='6px 8px 0 0'; a.style.padding='8px 10px'; a.style.border='1px solid #58a6ff'; a.style.borderRadius='10px'; a.style.color='#58a6ff'; box.prepend(a); } }
function saveSprite(){ if(!state.result){ alert('先に解析してください。'); return; } const p=renderV110(state.result); saveLink(p.canvas.toDataURL('image/png'), 'sprite_front_32_v1_10_mask_part_semantic.png', '画像を開く/保存 sprite_front_32_v1_10_mask_part_semantic.png'); }
function saveProject(){ if(!state.result){ alert('先に解析してください。'); return; } const p=renderV110(state.result); const obj={version:VERSION,type:'game_sprite_32_mask_part_semantic',renderer:'mask_part_semantic_v1_10',mode:p.mode,parts:Object.fromEntries(Object.entries(p.parts).filter(([,v])=>!!v).map(([k,v])=>[k,{size:{w:v.canvas.width,h:v.canvas.height},count:v.count,labels:v.labels}])),root_cause_fixed:['rectangular source crop contamination','hair dominating body','face giant with unreadable details'],goal:'use real extracted part pixels and semantic placement for a game-ready sprite'}; saveLink('data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(obj,null,2)), 'sprite_pixel_project_v1_10_mask_part_semantic.json', 'JSONを開く/保存 sprite_pixel_project_v1_10_mask_part_semantic.json'); }
function ensureStageOutputUi(){ const c32=qs10('cSprite32'); if(!c32) return; if(qs10('cSprite128') && qs10('cSprite64')) return; const panel=c32.closest('.card'); if(!panel) return; const grid=panel.querySelector('.spriteOutputGrid') || c32.parentElement?.parentElement; if(!grid) return; const wrap128=document.createElement('div'); wrap128.innerHTML='<div class="mini">128x128 再構成土台</div><canvas id="cSprite128" style="image-rendering:pixelated;width:128px;height:128px;border:1px solid #334155"></canvas>'; const wrap64=document.createElement('div'); wrap64.innerHTML='<div class="mini">64x64 中間段階</div><canvas id="cSprite64" style="image-rendering:pixelated;width:128px;height:128px;border:1px solid #334155"></canvas>'; grid.insertBefore(wrap128, grid.firstChild); grid.insertBefore(wrap64, c32.parentElement); const h2=panel.querySelector('h2'); if(h2 && h2.textContent.includes('32x32')) h2.childNodes[0].textContent='12. Sprite Output 128 → 64 → 32 '; }
function drawV110(){ if(!state.result) return; ensureStageOutputUi(); const pack=renderV110(state.result); const id=applyResult(state.result, pack); const c128=qs10('cSprite128'), c64=qs10('cSprite64'), c32=qs10('cSprite32'), prev=qs10('cSpritePreview'), st=qs10('spriteStatus'), log=qs10('pixelLog'); if(c128){ fit(c128,128,128); const ctx=c128.getContext('2d'); ctx.clearRect(0,0,128,128); ctx.imageSmoothingEnabled=false; ctx.drawImage(pack.stage128,0,0); } if(c64){ fit(c64,64,64); const ctx=c64.getContext('2d'); ctx.clearRect(0,0,64,64); ctx.imageSmoothingEnabled=false; ctx.drawImage(pack.stage64,0,0); } if(c32){ fit(c32,32,32); const ctx=c32.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.putImageData(id,0,0); } if(prev){ fit(prev,320,320); const ctx=prev.getContext('2d'); ctx.imageSmoothingEnabled=false; ctx.fillStyle='#0b111b'; ctx.fillRect(0,0,320,320); ctx.strokeStyle='rgba(255,255,255,.08)'; for(let i=0;i<=32;i++){ ctx.beginPath(); ctx.moveTo(i*10,0); ctx.lineTo(i*10,320); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0,i*10); ctx.lineTo(320,i*10); ctx.stroke(); } const t=document.createElement('canvas'); t.width=32; t.height=32; t.getContext('2d').putImageData(id,0,0); ctx.drawImage(t,0,0,320,320); } if(st) st.textContent='v1.10.2 stage display'; if(log){ const ps=Object.entries(pack.parts).filter(([,v])=>!!v).map(([k,v])=>`- ${k}: ${v.count} parts / ${v.canvas.width}x${v.canvas.height}`).join('\\n'); log.textContent=`Sprite v1.10.2\\nstatus=ok\\nrenderer=mask_part_semantic_v1_10\\nmode=${pack.mode}\\n\\n表示段階:\\n- 128x128: 部位再構成の土台\\n- 64x64: 色整理と中間圧縮\\n- 32x32: 最終ゲーム用出力\\n\\n修正:\\n- 既存HTMLでもJS側で128/64表示枠を自動追加\\n- script cache対策としてv1.10.2へ更新\\n- candidate pixels から部位マスクを直接生成\\n\\npart summary:\\n${ps}`; } }
function addModeUi(){ const bar=document.querySelector('.bar'); if(!bar) return; let sel=qs10('pixelMode'); if(!sel){ sel=document.createElement('select'); sel.id='pixelMode'; const run=qs10('run'); if(run) bar.insertBefore(sel,run); else bar.appendChild(sel); } sel.innerHTML='<option value="mask_part_semantic">ドット化:Cバランス 部位マスク再構成</option><option value="faithful">ドット化:元画像忠実</option>'; sel.value='mask_part_semantic'; sel.onchange=()=>{ if(state.result) drawV110(); }; }
function install(){ ensureStageOutputUi(); addModeUi(); const b1=qs10('saveSprite32'); if(b1) b1.onclick=saveSprite; const b2=qs10('savePixelProject'); if(b2) b2.onclick=saveProject; const oldAnalyze=(typeof analyze==='function') ? analyze : null; async function analyzeV110(){ if(oldAnalyze) await oldAnalyze(); try{ if(state.result) drawV110(); }catch(e){ console.warn('v1.10 draw failed',e); } } analyze=analyzeV110; window.analyzeV110=analyzeV110; const run=qs10('run'); if(run) run.onclick=analyzeV110; document.title='Sprite Studio Pixel Pipeline v1.10.2'; const h1=document.querySelector('h1'); if(h1) h1.textContent='Sprite Studio Pixel Pipeline v1.10.2'; const sub=document.querySelector('.sub'); if(sub) sub.textContent='AIなし / Canvas + localStorageのみ。v1.10.2: stage display cache fix。128/64/32表示をJS側でも自動追加します。'; const footer=document.querySelector('.footer'); if(footer) footer.textContent='v1.10.2 は stage display cache fix です。index差し替え漏れやJSキャッシュでも128/64表示が追加されるようにしました。'; }
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',install); else install();
if(typeof metadata092==='function'){ const oldMeta=metadata092; metadata092=function(){ const m=oldMeta(); m.version=VERSION; m.pixel_sprite_v110={status:state.result?.sprite32V110?.status||'not_run',renderer:'mask_part_semantic_v1_10',mode:state.result?.sprite32V110?.mode||null,parts:state.result?.sprite32V110?.parts||null}; return m; }; }
})();
