// ===== v1.11 patch: safe 128 rebuild renderer =====
(function(){
'use strict';
const VERSION='1.11-safe-128-rebuild';
function qs11(id){ return typeof qs==='function' ? qs(id) : document.getElementById(id); }
function fit(c,w,h){ c.width=w; c.height=h; }
function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }
function srcImg(res){ return res?.pre?.analysis || res?.imgData || state.orig; }
function mix(a,b,t){ return [Math.round(a[0]*(1-t)+b[0]*t),Math.round(a[1]*(1-t)+b[1]*t),Math.round(a[2]*(1-t)+b[2]*t),255]; }
function dark(c,t=.3){ return mix(c,[24,22,36,255],t); }
function light(c,t=.25){ return mix(c,[255,255,255,255],t); }
function avgColorCanvas(c, fallback=[180,180,180,255]){ if(!c) return fallback; const ctx=c.getContext('2d'), img=ctx.getImageData(0,0,c.width,c.height).data; let r=0,g=0,b=0,n=0; for(let i=0;i<img.length;i+=4){ if(img[i+3]<24) continue; r+=img[i]; g+=img[i+1]; b+=img[i+2]; n++; } return n?[Math.round(r/n),Math.round(g/n),Math.round(b/n),255]:fallback; }
function groupPixels(cands, labels){ const set=new Set(labels); return (cands||[]).filter(r=>set.has(r.label)); }
function partFromLabels(img, cands, labels, pad=2, opt={}){ const picks=groupPixels(cands, labels); if(!picks.length) return null; const w=img.width,h=img.height,d=img.data; let minx=w,miny=h,maxx=-1,maxy=-1; const mask=new Uint8Array(w*h); let used=0; for(const r of picks){ const bx=(r.maxx??((r.minx??0)+(r.w??0)-1))-(r.minx??0)+1; const by=(r.maxy??((r.miny??0)+(r.h??0)-1))-(r.miny??0)+1; if(opt.rejectVeryLarge && bx*by > w*h*0.72) continue; for(const p of (r.pixels||[])){ mask[p]=1; const x=p%w, y=(p/w)|0; if(x<minx)minx=x; if(y<miny)miny=y; if(x>maxx)maxx=x; if(y>maxy)maxy=y; used++; } }
 if(maxx<0 || used===0) return null; minx=clamp(minx-pad,0,w-1); miny=clamp(miny-pad,0,h-1); maxx=clamp(maxx+pad,0,w-1); maxy=clamp(maxy+pad,0,h-1); const pw=maxx-minx+1, ph=maxy-miny+1; const c=document.createElement('canvas'); fit(c,pw,ph); const ctx=c.getContext('2d'); const out=ctx.createImageData(pw,ph); for(let y=miny;y<=maxy;y++)for(let x=minx;x<=maxx;x++){ const p=y*w+x; if(!mask[p]) continue; const si=p*4, di=((y-miny)*pw+(x-minx))*4; out.data[di]=d[si]; out.data[di+1]=d[si+1]; out.data[di+2]=d[si+2]; out.data[di+3]=d[si+3]; } ctx.putImageData(out,0,0); return {canvas:c,bbox:{minx,miny,maxx,maxy,w:pw,h:ph},count:picks.length,labels,used}; }
function detectParts(res){ const img=srcImg(res), c=res?.candidates||[]; return {
  hair: partFromLabels(img,c,['hair','front_hair','side_hair_left','side_hair_right','back_hair','hair_soft','hair_tip','hair_highlight','hair_shadow'],3,{rejectVeryLarge:true}),
  face: partFromLabels(img,c,['face'],2),
  ears: partFromLabels(img,c,['ears'],1),
  eyes: partFromLabels(img,c,['eyes','eye_candidate'],1),
  neck: partFromLabels(img,c,['neck'],1),
  body: partFromLabels(img,c,['upper_cloth','lower_cloth','cloth_detail','collar'],2,{rejectVeryLarge:true}),
  sleeves: partFromLabels(img,c,['transparent_cloth','sleeve_left','sleeve_right','sheer','sheer_soft'],2,{rejectVeryLarge:true}),
  hands: partFromLabels(img,c,['hands','hand_candidate'],1),
  legs: partFromLabels(img,c,['left_leg','right_leg','leg','legs'],2),
  shoes: partFromLabels(img,c,['shoe','shoes','left_foot','right_foot'],1),
  ornaments: partFromLabels(img,c,['cloth_ornament','ornament_detail','body_ornament','necklace','belt'],1)
}; }
function drawCropFrac(ctx, part, fx, fy, fw, fh, dx, dy, dw, dh){ if(!part||!part.canvas||dw<=0||dh<=0) return; const c=part.canvas; const sx=clamp(Math.floor(c.width*fx),0,c.width-1), sy=clamp(Math.floor(c.height*fy),0,c.height-1); const sw=clamp(Math.floor(c.width*fw),1,c.width-sx), sh=clamp(Math.floor(c.height*fh),1,c.height-sy); ctx.drawImage(c,sx,sy,sw,sh,dx,dy,dw,dh); }
function drawScaled(ctx, part, dx, dy, dw, dh){ if(!part||!part.canvas||dw<=0||dh<=0) return; ctx.drawImage(part.canvas,0,0,part.canvas.width,part.canvas.height,dx,dy,dw,dh); }
function drawMirrorHalf(ctx, part, ldx,ldy,lw,lh, rdx,rdy,rw,rh){ if(!part) return; drawCropFrac(ctx,part,0,0,.48,1,ldx,ldy,lw,lh); drawCropFrac(ctx,part,.52,0,.48,1,rdx,rdy,rw,rh); }
function roundedFace(ctx,x,y,w,h,col){ ctx.fillStyle=`rgba(${col[0]},${col[1]},${col[2]},1)`; ctx.beginPath(); ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2); ctx.fill(); const hi=light(col,.22); ctx.fillStyle=`rgba(${hi[0]},${hi[1]},${hi[2]},.55)`; ctx.beginPath(); ctx.ellipse(x+w/2,y+h*.42,w*.34,h*.20,0,0,Math.PI*2); ctx.fill(); }
function drawFace128(ctx, parts){ const skin=avgColorCanvas(parts.face?.canvas,[232,185,170,255]); const hair=avgColorCanvas(parts.hair?.canvas,[170,160,190,255]); roundedFace(ctx,44,16,40,31,skin); drawScaled(ctx,parts.ears,34,22,60,16); drawScaled(ctx,parts.face,47,18,34,24); // source face texture, bounded
  // front hair should never cover more than top third of face
  drawCropFrac(ctx,parts.hair,.18,0,.64,.20,39,5,50,17);
  const eye=parts.eyes?avgColorCanvas(parts.eyes.canvas):dark(hair,.45); const ed=dark(eye,.2), eh=light(eye,.52); ctx.fillStyle=`rgba(${ed[0]},${ed[1]},${ed[2]},1)`; ctx.fillRect(53,27,4,5); ctx.fillRect(71,27,4,5); ctx.fillRect(51,26,4,2); ctx.fillRect(73,26,4,2); ctx.fillStyle=`rgba(${eh[0]},${eh[1]},${eh[2]},1)`; ctx.fillRect(54,27,2,2); ctx.fillRect(72,27,2,2); const blush=mix(skin,[236,138,170,255],.36); ctx.fillStyle=`rgba(${blush[0]},${blush[1]},${blush[2]},.9)`; ctx.fillRect(49,38,5,2); ctx.fillRect(75,38,5,2); const lip=mix(skin,[190,88,118,255],.55); ctx.fillStyle=`rgba(${lip[0]},${lip[1]},${lip[2]},1)`; ctx.fillRect(61,42,6,2); }
function addOutline(ctx,w,h,alpha=220){ const src=ctx.getImageData(0,0,w,h), out=ctx.getImageData(0,0,w,h), s=src.data,d=out.data; let sr=0,sg=0,sb=0,n=0; for(let i=0;i<s.length;i+=4){ if(s[i+3]>160){ sr+=s[i]; sg+=s[i+1]; sb+=s[i+2]; n++; } } const col=n?[Math.max(12,Math.round(sr/n*.24)),Math.max(12,Math.round(sg/n*.24)),Math.max(18,Math.round(sb/n*.28)),alpha]:[42,38,56,alpha]; for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){ const i=(y*w+x)*4; if(s[i+3]) continue; let near=0; for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){ if(!xx&&!yy) continue; if(s[((y+yy)*w+(x+xx))*4+3]>160) near++; } if(near>=2){ d[i]=col[0]; d[i+1]=col[1]; d[i+2]=col[2]; d[i+3]=col[3]; } } ctx.putImageData(out,0,0); }
function palette(ctx,w,h,k){ const d=ctx.getImageData(0,0,w,h).data; const bins=new Map(); for(let i=0;i<d.length;i+=4){ if(d[i+3]<18) continue; const key=((d[i]>>4)<<8)|((d[i+1]>>4)<<4)|(d[i+2]>>4); let o=bins.get(key); if(!o)o={n:0,r:0,g:0,b:0}; o.n++; o.r+=d[i]; o.g+=d[i+1]; o.b+=d[i+2]; bins.set(key,o); } return [...bins.values()].sort((a,b)=>b.n-a.n).slice(0,k).map(o=>[Math.round(o.r/o.n),Math.round(o.g/o.n),Math.round(o.b/o.n),255]); }
function nearest(c,pal){ let best=pal[0]||[0,0,0,0],bd=1e18; for(const p of pal){ const dr=c[0]-p[0],dg=c[1]-p[1],db=c[2]-p[2],dd=dr*dr+dg*dg+db*db; if(dd<bd){bd=dd;best=p;} } return best; }
function quantize(ctx,w,h,k){ const img=ctx.getImageData(0,0,w,h),d=img.data,pal=palette(ctx,w,h,k); for(let i=0;i<d.length;i+=4){ if(d[i+3]<20){ d[i]=d[i+1]=d[i+2]=d[i+3]=0; continue; } const p=nearest([d[i],d[i+1],d[i+2]],pal); d[i]=p[0]; d[i+1]=p[1]; d[i+2]=p[2]; d[i+3]=255; } ctx.putImageData(img,0,0); return pal; }
function drawFace32(ctx,parts){ const skin=avgColorCanvas(parts.face?.canvas,[232,185,170,255]); const hair=avgColorCanvas(parts.hair?.canvas,[170,160,190,255]); const fringe=dark(hair,.12); ctx.fillStyle=`rgba(${fringe[0]},${fringe[1]},${fringe[2]},1)`; ctx.fillRect(10,4,12,2); ctx.fillRect(12,6,8,1); const eye=parts.eyes?avgColorCanvas(parts.eyes.canvas):dark(hair,.45), ed=dark(eye,.15), eh=light(eye,.50); ctx.fillStyle=`rgba(${ed[0]},${ed[1]},${ed[2]},1)`; ctx.fillRect(13,9,1,2); ctx.fillRect(18,9,1,2); ctx.fillRect(12,9,1,1); ctx.fillRect(19,9,1,1); ctx.fillStyle=`rgba(${eh[0]},${eh[1]},${eh[2]},1)`; ctx.fillRect(13,9,1,1); ctx.fillRect(18,9,1,1); const blush=mix(skin,[236,138,170,255],.36); ctx.fillStyle=`rgba(${blush[0]},${blush[1]},${blush[2]},.95)`; ctx.fillRect(12,12,1,1); ctx.fillRect(19,12,1,1); const lip=mix(skin,[190,88,118,255],.55); ctx.fillStyle=`rgba(${lip[0]},${lip[1]},${lip[2]},1)`; ctx.fillRect(15,13,2,1); }
function compose128(parts){ const c=document.createElement('canvas'); fit(c,128,128); const ctx=c.getContext('2d'); ctx.clearRect(0,0,128,128); ctx.imageSmoothingEnabled=true;
  // safe layout: body skeleton first, hair capped and split. No full huge hair rectangle.
  const hairC=avgColorCanvas(parts.hair?.canvas,[170,160,190,255]);
  // back hair halo, limited to head + upper side locks only
  drawCropFrac(ctx,parts.hair,.15,0,.70,.48,30,2,68,48);
  drawCropFrac(ctx,parts.hair,0,.20,.28,.70,18,24,18,62);
  drawCropFrac(ctx,parts.hair,.72,.20,.28,.70,92,24,18,62);
  if(!parts.hair){ const hc=hairC; ctx.fillStyle=`rgba(${hc[0]},${hc[1]},${hc[2]},.9)`; ctx.beginPath(); ctx.ellipse(64,28,34,28,0,0,Math.PI*2); ctx.fill(); }
  // sleeves behind body, capped
  if(parts.sleeves){ drawMirrorHalf(ctx,parts.sleeves,22,52,16,46,90,52,16,46); }
  // readable core body/legs
  drawScaled(ctx,parts.body,45,53,38,36);
  drawScaled(ctx,parts.ornaments,51,56,26,16);
  drawScaled(ctx,parts.legs,50,86,28,30);
  drawScaled(ctx,parts.shoes,50,113,28,10);
  drawScaled(ctx,parts.neck,55,43,18,10);
  drawFace128(ctx,parts);
  if(parts.hands){ drawMirrorHalf(ctx,parts.hands,31,70,8,14,89,70,8,14); }
  // small grounding shadow
  ctx.fillStyle='rgba(0,0,0,.18)'; ctx.fillRect(45,124,38,3);
  return c; }
function compose64(stage128){ const c=document.createElement('canvas'); fit(c,64,64); const ctx=c.getContext('2d'); ctx.clearRect(0,0,64,64); ctx.imageSmoothingEnabled=true; ctx.drawImage(stage128,0,0,64,64); quantize(ctx,64,64,clamp(parseInt(qs11('k')?.value||'8',10)+2,6,14)); addOutline(ctx,64,64,180); return c; }
function compose32(stage64,parts){ const c=document.createElement('canvas'); fit(c,32,32); const ctx=c.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.imageSmoothingEnabled=true; ctx.drawImage(stage64,0,0,32,32); quantize(ctx,32,32,clamp(parseInt(qs11('k')?.value||'8',10)+1,5,12)); addOutline(ctx,32,32,220); drawFace32(ctx,parts); return c; }
function renderV111(res){ const parts=detectParts(res); const stage128=compose128(parts); const stage64=compose64(stage128); const canvas=compose32(stage64,parts); return {parts,stage128,stage64,canvas,mode:'safe128_rebuild'}; }
function applyResult(res, pack){ const id=pack.canvas.getContext('2d').getImageData(0,0,32,32); const partSummary={}; for(const [k,v] of Object.entries(pack.parts||{})){ if(v) partSummary[k]={w:v.canvas.width,h:v.canvas.height,count:v.count,used:v.used}; } const payload={imageData:id,status:'ok',renderer:'safe128_rebuild_v1_11',mode:pack.mode,parts:partSummary,note:'128 stage rebuilt with capped hair, protected face frame, and readable body skeleton'}; res.sprite32V111=payload; res.sprite32V110=payload; res.sprite32V19=payload; res.sprite32V10=res.sprite32V10||{}; res.sprite32V10.imageData=id; res.sprite32V10.status='ok-v1.11'; return id; }
function saveLink(dataUrl,name,label){ try{ const a=document.createElement('a'); a.href=dataUrl; a.download=name; document.body.appendChild(a); a.click(); setTimeout(()=>a.remove(),400); }catch(e){} const log=qs11('pixelLog')||qs11('log'); if(log){ let box=document.getElementById('saveLinksV111'); if(!box){ box=document.createElement('div'); box.id='saveLinksV111'; box.style.marginTop='10px'; log.parentNode.appendChild(box); } const a=document.createElement('a'); a.href=dataUrl; a.download=name; a.target='_blank'; a.rel='noopener'; a.textContent=label||name; a.style.display='inline-block'; a.style.margin='6px 8px 0 0'; a.style.padding='8px 10px'; a.style.border='1px solid #58a6ff'; a.style.borderRadius='10px'; a.style.color='#58a6ff'; box.prepend(a); } }
function saveSprite(){ if(!state.result){ alert('先に解析してください。'); return; } const p=renderV111(state.result); saveLink(p.canvas.toDataURL('image/png'),'sprite_front_32_v1_11_safe128.png','画像を開く/保存 sprite_front_32_v1_11_safe128.png'); }
function saveProject(){ if(!state.result){ alert('先に解析してください。'); return; } const p=renderV111(state.result); const obj={version:VERSION,type:'game_sprite_32_safe128_rebuild',renderer:'safe128_rebuild_v1_11',mode:p.mode,parts:Object.fromEntries(Object.entries(p.parts).filter(([,v])=>!!v).map(([k,v])=>[k,{size:{w:v.canvas.width,h:v.canvas.height},count:v.count,used:v.used}])),fix:['remove soft_shell from hair','do not draw full hair rectangle','cap side hair and front hair','protect face frame','body skeleton visible before final downscale']}; saveLink('data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(obj,null,2)),'sprite_pixel_project_v1_11_safe128.json','JSONを開く/保存 sprite_pixel_project_v1_11_safe128.json'); }
function drawV111(){ if(!state.result) return; const p=renderV111(state.result); const id=applyResult(state.result,p); const c128=qs11('cSprite128'), c64=qs11('cSprite64'), c32=qs11('cSprite32'), prev=qs11('cSpritePreview'), st=qs11('spriteStatus'), log=qs11('pixelLog'); if(c128){ fit(c128,128,128); const ctx=c128.getContext('2d'); ctx.clearRect(0,0,128,128); ctx.imageSmoothingEnabled=false; ctx.drawImage(p.stage128,0,0); } if(c64){ fit(c64,64,64); const ctx=c64.getContext('2d'); ctx.clearRect(0,0,64,64); ctx.imageSmoothingEnabled=false; ctx.drawImage(p.stage64,0,0); } if(c32){ fit(c32,32,32); const ctx=c32.getContext('2d'); ctx.clearRect(0,0,32,32); ctx.putImageData(id,0,0); } if(prev){ fit(prev,320,320); const ctx=prev.getContext('2d'); ctx.imageSmoothingEnabled=false; ctx.fillStyle='#0b111b'; ctx.fillRect(0,0,320,320); ctx.strokeStyle='rgba(255,255,255,.08)'; for(let i=0;i<=32;i++){ ctx.beginPath(); ctx.moveTo(i*10,0); ctx.lineTo(i*10,320); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0,i*10); ctx.lineTo(320,i*10); ctx.stroke(); } const t=document.createElement('canvas'); t.width=32; t.height=32; t.getContext('2d').putImageData(id,0,0); ctx.drawImage(t,0,0,320,320); } if(st) st.textContent='v1.11 safe128'; if(log){ const ps=Object.entries(p.parts).filter(([,v])=>!!v).map(([k,v])=>`- ${k}: ${v.canvas.width}x${v.canvas.height} / used ${v.used}`).join('\n'); log.textContent=`Sprite v1.11\nstatus=ok\nrenderer=safe128_rebuild_v1_11\nmode=${p.mode}\n\n今回の判断:\n- 前回の修正だけでは不十分。髪をfull rectangleで置く限り128で崩れる。\n- なので128段階を安全配置に作り直した。\n\n修正:\n- soft_shellを髪から除外\n- full hair rectangleを廃止\n- 髪は頭上/左右サイド/前髪に分け、サイズ上限をかける\n- 顔フレームを固定確保して目を128/32で再描画\n- 胴体と脚を先に読めるサイズで配置\n\npart summary:\n${ps}`; } }
function addModeUi(){ const bar=document.querySelector('.bar'); if(!bar) return; let sel=qs11('pixelMode'); if(!sel){ sel=document.createElement('select'); sel.id='pixelMode'; const run=qs11('run'); if(run) bar.insertBefore(sel,run); else bar.appendChild(sel); } sel.innerHTML='<option value="safe128_rebuild">ドット化:Cバランス 安全128再構成</option><option value="mask_part_semantic">ドット化:Cバランス 部位マスク再構成</option><option value="faithful">ドット化:元画像忠実</option>'; sel.value='safe128_rebuild'; sel.onchange=()=>{ if(state.result) drawV111(); }; }
function install(){ addModeUi(); const b1=qs11('saveSprite32'); if(b1) b1.onclick=saveSprite; const b2=qs11('savePixelProject'); if(b2) b2.onclick=saveProject; const oldAnalyze=(typeof analyze==='function')?analyze:null; async function analyzeV111(){ if(oldAnalyze) await oldAnalyze(); try{ if(state.result) drawV111(); }catch(e){ console.warn('v1.11 draw failed',e); } } analyze=analyzeV111; window.analyzeV111=analyzeV111; const run=qs11('run'); if(run) run.onclick=analyzeV111; document.title='Sprite Studio Pixel Pipeline v1.11'; const h1=document.querySelector('h1'); if(h1) h1.textContent='Sprite Studio Pixel Pipeline v1.11'; const sub=document.querySelector('.sub'); if(sub) sub.textContent='AIなし / Canvas + localStorageのみ。v1.11: safe 128 rebuild。128段階の破綻を抑えるため、髪を分割配置し顔と胴体を保護します。'; const footer=document.querySelector('.footer'); if(footer) footer.textContent='v1.11 は safe 128 rebuild renderer です。128の土台が崩れないように、髪・顔・胴体の配置制限を入れました。'; }
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',install); else install();
if(typeof metadata092==='function'){ const oldMeta=metadata092; metadata092=function(){ const m=oldMeta(); m.version=VERSION; m.pixel_sprite_v111={status:state.result?.sprite32V111?.status||'not_run',renderer:'safe128_rebuild_v1_11',mode:state.result?.sprite32V111?.mode||null,parts:state.result?.sprite32V111?.parts||null}; return m; }; }
})();
