(function(){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const cv=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
const id=(c)=>c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height);
const from=(im)=>{const c=cv(im.width,im.height);c.getContext('2d').putImageData(im,0,0);return c};
function drawContain(img,size=512){const c=cv(size,size),x=c.getContext('2d');x.clearRect(0,0,size,size);const s=Math.min((size*.92)/img.width,(size*.92)/img.height),w=img.width*s,h=img.height*s;x.drawImage(img,(size-w)/2,(size-h)/2,w,h);return c}
function borderModel(im){const d=im.data,w=im.width,h=im.height,s=[];const push=(x,y)=>{const i=(y*w+x)*4;if(d[i+3]>0)s.push([d[i],d[i+1],d[i+2]])};for(let x=0;x<w;x+=4){push(x,0);push(x,h-1)}for(let y=0;y<h;y+=4){push(0,y);push(w-1,y)};s.sort((a,b)=>(a[0]+a[1]+a[2])-(b[0]+b[1]+b[2]));const m=s[Math.floor(s.length*.6)]||[255,255,255];let dev=0;for(const p of s)dev+=Math.hypot(p[0]-m[0],p[1]-m[1],p[2]-m[2]);dev/=Math.max(1,s.length);return {rgb:m,tol:clamp(dev*1.8+24,30,88)}}
function removeBackground(src,opt={}){const im=id(src),d=im.data,w=im.width,h=im.height,{rgb,tol}=borderModel(im),seen=new Uint8Array(w*h),q=new Int32Array(w*h),head=0,tail=0;const dist=(i)=>{const dr=d[i]-rgb[0],dg=d[i+1]-rgb[1],db=d[i+2]-rgb[2];return Math.sqrt(.45*dr*dr+.45*dg*dg+.10*db*db)};const add=(x,y)=>{const p=y*w+x;if(seen[p])return;seen[p]=1;q[tail++]=p};for(let x=0;x<w;x++){add(x,0);add(x,h-1)}for(let y=0;y<h;y++){add(0,y);add(w-1,y)};while(head<tail){const p=q[head++],x=p%w,y=(p/w)|0,i=p*4;if(dist(i)>tol)continue;d[i+3]=0;if(x>0)add(x-1,y);if(x<w-1)add(x+1,y);if(y>0)add(x,y-1);if(y<h-1)add(x,y+1)}
// Remove neutral bright backdrop islands that decorative rings may disconnect from the border.
for(let p=0;p<w*h;p++){const i=p*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx>225&&mx-mn<26)d[i+3]=0;}
// Remove near-background halos only when already close to transparent frontier.
for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=y*w+x,i=p*4;if(!d[i+3])continue;let z=0;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++)if(d[((y+oy)*w+x+ox)*4+3]===0)z++;if(z&&dist(i)<tol*1.25)d[i+3]=clamp(Math.round((dist(i)-tol*.75)/(tol*.5)*255),0,255)}
return from(im)}
function bounds(c){const im=id(c),d=im.data,w=im.width,h=im.height;let x0=w,y0=h,x1=-1,y1=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>18){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y)}return x1<0?{x:0,y:0,w,h}:{x:x0,y:y0,w:x1-x0+1,h:y1-y0+1}}
function premulSample(im,x,y){const w=im.width,h=im.height,d=im.data;x=clamp(x,0,w-1);y=clamp(y,0,h-1);const x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(w-1,x0+1),y1=Math.min(h-1,y0+1),tx=x-x0,ty=y-y0;let pr=0,pg=0,pb=0,a=0;for(const [xx,yy,ww] of [[x0,y0,(1-tx)*(1-ty)],[x1,y0,tx*(1-ty)],[x0,y1,(1-tx)*ty],[x1,y1,tx*ty]]){const i=(yy*w+xx)*4,aa=d[i+3]/255;a+=aa*ww;pr+=d[i]*aa*ww;pg+=d[i+1]*aa*ww;pb+=d[i+2]*aa*ww}if(a<.001)return [0,0,0,0];return [pr/a,pg/a,pb/a,a*255]}
function profileY(t,p){const headEnd=.26, torsoEnd=.63;let y;if(t<headEnd)y=t*(p.headY);else if(t<torsoEnd)y=headEnd*p.headY+(t-headEnd)*p.torsoY;else y=headEnd*p.headY+(torsoEnd-headEnd)*p.torsoY+(t-torsoEnd)*p.legY;const total=headEnd*p.headY+(torsoEnd-headEnd)*p.torsoY+(1-torsoEnd)*p.legY;return y/total}
function inverseProfileY(v,p){let lo=0,hi=1;for(let k=0;k<18;k++){const m=(lo+hi)/2;if(profileY(m,p)<v)lo=m;else hi=m}return (lo+hi)/2}
function widthScale(t,p){const a=p.headX,b=p.torsoX,c=p.legX;if(t<.22)return a;if(t<.32){const u=(t-.22)/.10;return a*(1-u)+b*u}if(t<.63)return b;if(t<.74){const u=(t-.63)/.11;return b*(1-u)+c*u}return c}
function continuousDeform(src,p){const b=bounds(src),out=cv(src.width,src.height),o=out.getContext('2d').createImageData(out.width,out.height),sim=id(src),cx=b.x+b.w/2;const targetH=b.h*(.26*p.headY+.37*p.torsoY+.37*p.legY),top=b.y+(b.h-targetH)*.52;for(let y=Math.max(0,Math.floor(top-4));y<Math.min(out.height,Math.ceil(top+targetH+4));y++){const v=(y-top)/targetH;if(v<0||v>1)continue;const t=inverseProfileY(v,p),sy=b.y+t*b.h,ws=widthScale(t,p);for(let x=0;x<out.width;x++){const sx=cx+(x-cx)/ws;const px=premulSample(sim,sx,sy),i=(y*out.width+x)*4;o.data[i]=px[0];o.data[i+1]=px[1];o.data[i+2]=px[2];o.data[i+3]=px[3]}}out.getContext('2d').putImageData(o,0,0);return out}
function cropFit(src,size,pad=.08){const b=bounds(src),c=cv(size,size),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';const s=Math.min(size*(1-pad*2)/b.w,size*(1-pad*2)/b.h),w=b.w*s,h=b.h*s;x.drawImage(src,b.x,b.y,b.w,b.h,(size-w)/2,(size-h)/2,w,h);return c}
function quantize(src,colors=40){const im=id(src),d=im.data;const levels=Math.max(2,Math.round(Math.cbrt(colors)));const step=255/(levels-1);for(let i=0;i<d.length;i+=4){if(d[i+3]<12){d[i]=d[i+1]=d[i+2]=d[i+3]=0;continue}d[i]=Math.round(d[i]/step)*step;d[i+1]=Math.round(d[i+1]/step)*step;d[i+2]=Math.round(d[i+2]/step)*step;d[i+3]=d[i+3]>160?255:(d[i+3]>48?128:0)}return from(im)}
function edgeClean(src){const im=id(src),d=im.data,w=im.width,h=im.height,copy=new Uint8ClampedArray(d);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;if(copy[i+3]===0)continue;let n=0;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++)if(copy[((y+oy)*w+x+ox)*4+3]>0)n++;if(n<=2)d[i+3]=0}return from(im)}
function nearestScale(src,size){const c=cv(size,size),x=c.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(src,0,0,size,size);return c}
function process(img,opt={}){const source=drawContain(img,512),cut=removeBackground(source,opt),p={headX:opt.headX||1.18,headY:opt.headY||1.05,torsoX:opt.torsoX||1.03,torsoY:opt.torsoY||.72,legX:opt.legX||1.02,legY:opt.legY||.55};const warped=continuousDeform(cut,p);let c128=cropFit(warped,128,.07);c128=edgeClean(quantize(c128,opt.colors||48));const c64=edgeClean(quantize(nearestScale(c128,64),32));const c32=edgeClean(quantize(nearestScale(c64,32),20));return {source,cut,warped,c128,c64,c32,params:p}}
window.RuleBasedSD={process,removeBackground,continuousDeform,quantize,VERSION:'1.18.0'};
})();
