'use strict';
(() => {
const $=id=>document.getElementById(id);
const src=$('sourceCanvas'), out=$('outputCanvas');
const sctx=src.getContext('2d',{willReadFrequently:true}), octx=out.getContext('2d',{willReadFrequently:true});
const state={image:null,base:null,scale:1,ox:0,oy:0,mode:'keep',painting:false,masks:null,last:null};
function status(s){$('status').textContent=s}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function loadBlob(blob,name='画像'){
 return new Promise((resolve,reject)=>{
  if(!blob||!/^image\/(png|jpeg|webp)$/i.test(blob.type||'')) return reject(new Error('PNG/JPG/WEBPを選択してください'));
  const finish=img=>{state.image=img; drawSource(); status(`${name} を読み込みました (${img.width}×${img.height})`); resolve(img)};
  if('createImageBitmap' in window){createImageBitmap(blob,{imageOrientation:'from-image'}).then(finish).catch(()=>fallback(blob,finish,reject));}
  else fallback(blob,finish,reject);
 });
}
function fallback(blob,ok,ng){const r=new FileReader();r.onerror=()=>ng(new Error('ファイル読込失敗'));r.onload=()=>{const im=new Image();im.onload=()=>ok(im);im.onerror=()=>ng(new Error('画像デコード失敗'));im.src=r.result};r.readAsDataURL(blob)}
function drawSource(){
 const im=state.image;if(!im)return;const max=520, sc=Math.min(max/im.width,max/im.height,1);src.width=Math.max(1,Math.round(im.width*sc));src.height=Math.max(1,Math.round(im.height*sc));state.scale=sc;state.ox=0;state.oy=0;sctx.clearRect(0,0,src.width,src.height);sctx.drawImage(im,0,0,src.width,src.height);state.base=sctx.getImageData(0,0,src.width,src.height);state.masks={keep:new Uint8Array(src.width*src.height),remove:new Uint8Array(src.width*src.height),protect:new Uint8Array(src.width*src.height)};renderSourceOverlay();
}
function renderSourceOverlay(){if(!state.base)return;sctx.putImageData(state.base,0,0);const id=sctx.getImageData(0,0,src.width,src.height),d=id.data,m=state.masks;for(let i=0;i<m.keep.length;i++){let r=0,g=0,b=0,a=0;if(m.keep[i]){g=220;a=.35}if(m.remove[i]){r=240;a=.38}if(m.protect[i]){b=240;a=.38}if(a){let p=i*4;d[p]=d[p]*(1-a)+r*a;d[p+1]=d[p+1]*(1-a)+g*a;d[p+2]=d[p+2]*(1-a)+b*a}}sctx.putImageData(id,0,0)}
function pos(e){const r=src.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*src.width/r.width,y:(t.clientY-r.top)*src.height/r.height}}
function paint(p){if(!state.masks)return;const rad=+$('brushSize').value/2,w=src.width,h=src.height,m=state.masks;for(let y=Math.max(0,Math.floor(p.y-rad));y<Math.min(h,Math.ceil(p.y+rad));y++)for(let x=Math.max(0,Math.floor(p.x-rad));x<Math.min(w,Math.ceil(p.x+rad));x++){if((x-p.x)**2+(y-p.y)**2>rad*rad)continue;const i=y*w+x;if(state.mode==='erase'){m.keep[i]=m.remove[i]=m.protect[i]=0}else{m[state.mode][i]=255;if(state.mode==='keep')m.remove[i]=0;if(state.mode==='remove')m.keep[i]=0}}renderSourceOverlay()}
['pointerdown','pointermove','pointerup','pointercancel'].forEach(ev=>src.addEventListener(ev,e=>{if(ev==='pointerdown'){state.painting=true;src.setPointerCapture?.(e.pointerId);paint(pos(e))}else if(ev==='pointermove'&&state.painting)paint(pos(e));else state.painting=false;e.preventDefault()}));
function colorDist(d,p,q){const dr=d[p]-d[q],dg=d[p+1]-d[q+1],db=d[p+2]-d[q+2];return Math.sqrt(dr*dr+dg*dg+db*db)}
function cutout(id,tol){const {width:w,height:h,data:d}=id,n=w*h,bg=new Uint8Array(n),q=new Int32Array(n),refs=[];for(let x=0;x<w;x++){refs.push(x,(h-1)*w+x)}for(let y=1;y<h-1;y++){refs.push(y*w,y*w+w-1)}
 // border median-like representative samples
 const samples=[];for(let k=0;k<refs.length;k+=Math.max(1,Math.floor(refs.length/64))){const p=refs[k]*4;samples.push([d[p],d[p+1],d[p+2]])}
 function isBg(i){if(state.masks.keep[i])return false;if(state.masks.remove[i])return true;const p=i*4;if(d[p+3]<12)return true;let best=1e9;for(const c of samples){const dr=d[p]-c[0],dg=d[p+1]-c[1],db=d[p+2]-c[2];best=Math.min(best,Math.sqrt(dr*dr+dg*dg+db*db))}const mx=Math.max(d[p],d[p+1],d[p+2]),mn=Math.min(d[p],d[p+1],d[p+2]);return best<tol || (mn>225&&mx-mn<18)}
 let head=0,tail=0;for(const i of refs){if(!bg[i]&&isBg(i)){bg[i]=1;q[tail++]=i}}while(head<tail){const i=q[head++],x=i%w,y=(i/w)|0;const ns=[i-1,i+1,i-w,i+w];for(const j of ns){if(j<0||j>=n||bg[j])continue;const xx=j%w,yy=(j/w)|0;if(Math.abs(xx-x)+Math.abs(yy-y)!==1)continue;if(isBg(j)){bg[j]=1;q[tail++]=j}}}
 const alpha=new Uint8Array(n);for(let i=0;i<n;i++)alpha[i]=bg[i]?0:d[i*4+3];
 // keep largest meaningful connected foreground components, but retain protected pixels
 const seen=new Uint8Array(n), comps=[];for(let i=0;i<n;i++){if(seen[i]||alpha[i]<20)continue;let st=[i],pix=[];seen[i]=1;while(st.length){const v=st.pop();pix.push(v);const x=v%w,y=(v/w)|0;for(const j of [v-1,v+1,v-w,v+w]){if(j<0||j>=n||seen[j]||alpha[j]<20)continue;const xx=j%w,yy=(j/w)|0;if(Math.abs(xx-x)+Math.abs(yy-y)!==1)continue;seen[j]=1;st.push(j)}}comps.push(pix)}comps.sort((a,b)=>b.length-a.length);const minKeep=Math.max(12,(comps[0]?.length||0)*.002);for(const c of comps.slice(1))if(c.length<minKeep&&!c.some(i=>state.masks.protect[i]))for(const i of c)alpha[i]=0;
 return alpha}
function bounds(alpha,w,h){let x0=w,y0=h,x1=-1,y1=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(alpha[y*w+x]>20){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y)}return x1<0?null:{x0,y0,x1,y1,w:x1-x0+1,h:y1-y0+1}}
function analyze(alpha,id,b){const w=id.width,h=id.height,rows=[];for(let y=b.y0;y<=b.y1;y++){let lo=w,hi=-1,count=0;for(let x=b.x0;x<=b.x1;x++)if(alpha[y*w+x]>20){lo=Math.min(lo,x);hi=Math.max(hi,x);count++}rows.push({y,lo,hi,count,width:hi>=lo?hi-lo+1:0})}
 const topN=Math.max(4,Math.floor(rows.length*.38));let maxTop=0,maxY=b.y0;for(const r of rows.slice(0,topN))if(r.width>maxTop){maxTop=r.width;maxY=r.y}
 // head end: first stable narrowing below widest head, bounded to generic range
 let headEnd=Math.round(b.y0+b.h*.31);for(const r of rows){const rel=(r.y-b.y0)/b.h;if(rel>.20&&rel<.43&&r.width<maxTop*.72){headEnd=r.y;break}}
 const shoulder=Math.round(headEnd+b.h*.05), waist=Math.round(b.y0+b.h*.60), ground=b.y1;return{cx:(b.x0+b.x1)/2,headEnd,shoulder,waist,ground,maxTop}}
function reconstruct(id,alpha,b,a,ratio){const sw=id.width,sd=id.data,W=128,H=128,od=new Uint8ClampedArray(W*H*4);const margin=5,targetH=118,headH=targetH/ratio,bodyH=targetH-headH;const srcHead=Math.max(1,a.headEnd-b.y0),srcBody=Math.max(1,b.y1-a.headEnd);let headScale=Math.min((W-12)/Math.max(1,a.maxTop),headH/srcHead*1.08);headScale=clamp(headScale,.65,2.2);const bodyWidthTarget=Math.min(W-18,b.w*(bodyH/srcBody)*1.12),bodyScale=clamp(bodyWidthTarget/b.w,.45,1.35);const dstHead1=margin+headH,dstGround=margin+targetH;
 function invY(dy){if(dy<=dstHead1)return b.y0+(dy-margin)/headH*srcHead;const u=clamp((dy-dstHead1)/bodyH,0,1);let t;if(u<.68)t=(u/.68)*.58;else t=.58+((u-.68)/.32)*.42;return a.headEnd+t*srcBody}
 function xScale(y){const t=(y-b.y0)/b.h;if(y<=a.headEnd)return headScale;if(t<.62)return bodyScale*(1.02-.10*((t-.31)/.31));return bodyScale*(.93+.07*((t-.62)/.38))}
 // inverse map: destination pixels sample the source, avoiding horizontal tearing and pinholes
 for(let dy=margin;dy<=dstGround;dy++){const sy=invY(dy),yi=clamp(Math.round(sy),b.y0,b.y1),sc=xScale(sy);for(let dx=1;dx<W-1;dx++){const sx=a.cx+(dx-64)/sc,xi=Math.round(sx);if(xi<b.x0||xi>b.x1)continue;const si=yi*sw+xi,aa=alpha[si];if(aa<20)continue;const p=(dy*W+dx)*4,s=si*4;od[p]=sd[s];od[p+1]=sd[s+1];od[p+2]=sd[s+2];od[p+3]=aa}}
 // protected details are re-splatted over inverse warp so thin weapons/hair survive
 for(let y=b.y0;y<=b.y1;y++)for(let x=b.x0;x<=b.x1;x++){const si=y*sw+x;if(!state.masks.protect[si]||alpha[si]<20)continue;let dy;if(y<=a.headEnd)dy=margin+(y-b.y0)/srcHead*headH;else{const t=(y-a.headEnd)/srcBody,band=t<.58?(t/.58)*.68:.68+((t-.58)/.42)*.32;dy=dstHead1+band*bodyH}const dx=64+(x-a.cx)*xScale(y);for(let yy=Math.round(dy)-1;yy<=Math.round(dy)+1;yy++)for(let xx=Math.round(dx)-1;xx<=Math.round(dx)+1;xx++){if(xx<0||xx>=W||yy<0||yy>=H)continue;const p=(yy*W+xx)*4,s=si*4;od[p]=sd[s];od[p+1]=sd[s+1];od[p+2]=sd[s+2];od[p+3]=alpha[si]}}
 // topology cleanup: fill only one-pixel enclosed holes, never blur open edges
 for(let pass=0;pass<2;pass++){const cp=od.slice();for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++){const p=(y*W+x)*4;if(cp[p+3])continue;const ns=[p-4,p+4,p-W*4,p+W*4].filter(q=>cp[q+3]>100);if(ns.length>=3){od[p]=Math.round(ns.reduce((s,q)=>s+cp[q],0)/ns.length);od[p+1]=Math.round(ns.reduce((s,q)=>s+cp[q+1],0)/ns.length);od[p+2]=Math.round(ns.reduce((s,q)=>s+cp[q+2],0)/ns.length);od[p+3]=255}}}
 return new ImageData(od,W,H)}
function quantize(img,levels=5){const d=img.data;for(let i=0;i<d.length;i+=4){if(d[i+3]<20){d[i]=d[i+1]=d[i+2]=0;d[i+3]=0;continue}const lum=.299*d[i]+.587*d[i+1]+.114*d[i+2];const step=255/(levels-1); // preserve hue with luminance buckets
 const q=Math.round(lum/step)*step,fac=lum?clamp(q/lum,.68,1.32):1;d[i]=clamp(Math.round(d[i]*fac),0,255);d[i+1]=clamp(Math.round(d[i+1]*fac),0,255);d[i+2]=clamp(Math.round(d[i+2]*fac),0,255);d[i+3]=255}return img}
function outline(img){const {width:w,height:h,data:d}=img,cp=d.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=(y*w+x)*4;if(cp[p+3])continue;let near=-1;for(const q of [p-4,p+4,p-w*4,p+w*4])if(cp[q+3]>150){near=q;break}if(near>=0){d[p]=Math.round(cp[near]*.20);d[p+1]=Math.round(cp[near+1]*.20);d[p+2]=Math.round(cp[near+2]*.25);d[p+3]=255}}return img}
function templateFace(img){const d=img.data,w=img.width,h=img.height; // generic skin estimate in upper 45%
 let sx=0,sy=0,n=0,minx=w,maxx=0,miny=h,maxy=0;for(let y=8;y<58;y++)for(let x=20;x<108;x++){const p=(y*w+x)*4,r=d[p],g=d[p+1],b=d[p+2];if(d[p+3]>0&&r>125&&r>g*1.03&&g>b*.92&&r-b>20){sx+=x;sy+=y;n++;minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y)}}if(n<20)return false;const cx=sx/n,cy=sy/n,fw=clamp(maxx-minx,18,48),eyeY=Math.round(cy-1),gap=Math.round(fw*.18),ew=clamp(Math.round(fw*.12),2,5),eh=clamp(Math.round(ew*1.5),3,7);const iris=[65,55,88];for(const ex of [Math.round(cx-gap),Math.round(cx+gap)]){for(let yy=-eh;yy<=eh;yy++)for(let xx=-ew;xx<=ew;xx++){if((xx/ew)**2+(yy/eh)**2>1)continue;const p=((eyeY+yy)*w+ex+xx)*4;if(p<0||p>=d.length)continue;if(Math.abs(xx)<ew*.7&&yy>-eh*.5){d[p]=iris[0];d[p+1]=iris[1];d[p+2]=iris[2];d[p+3]=255}else{d[p]=35;d[p+1]=29;d[p+2]=47;d[p+3]=255}}const hp=((eyeY-2)*w+ex-1)*4;d[hp]=d[hp+1]=d[hp+2]=245;d[hp+3]=255}const mp=((Math.round(cy+fw*.18))*w+Math.round(cx))*4;d[mp]=150;d[mp+1]=75;d[mp+2]=82;d[mp+3]=255;return true}
function run(){try{if(!state.base)throw new Error('先に画像を選択してください');status('解析・再構築中…');const id=new ImageData(new Uint8ClampedArray(state.base.data),state.base.width,state.base.height),alpha=cutout(id,+$('bgTol').value),b=bounds(alpha,id.width,id.height);if(!b||b.w<5||b.h<5)throw new Error('キャラクター領域を検出できません。背景許容を下げるか「残す」で補正してください。');const a=analyze(alpha,id,b),ratio=+$('ratio').value;let res=reconstruct(id,alpha,b,a,ratio);if($('faceMode').value==='template')templateFace(res);res=outline(quantize(res,6));octx.clearRect(0,0,128,128);octx.putImageData(res,0,0);status(`生成完了\n頭身: ${ratio.toFixed(1)} / 領域: ${b.w}×${b.h}\n推定: 頭末端 y=${a.headEnd}, 腰 y=${a.waist}\nOpenCV: ${window.cv&&window.cv.Mat?'有効':'純JSフォールバック'}`);window.__LAST_RESULT__=res;return true}catch(e){console.error(e);status('エラー: '+e.message);return false}}
function downloadCanvas(c,name){c.toBlob(b=>{if(!b)return;const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)},'image/png')}
$('fileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{await loadBlob(f,f.name)}catch(err){status('エラー: '+err.message)}finally{e.target.value=''}});
$('sampleBtn').onclick=async()=>{try{const r=await fetch('sample/input_character.jpg',{cache:'no-store'});if(!r.ok)throw new Error('サンプル取得失敗');await loadBlob(await r.blob(),'サンプル画像');run()}catch(e){status('エラー: '+e.message)}};
$('runBtn').onclick=run;$('resetBtn').onclick=()=>{if(state.masks){for(const m of Object.values(state.masks))m.fill(0);renderSourceOverlay();status('手動補正を消去しました')}};
$('ratio').oninput=e=>{$('ratioOut').value=(+e.target.value).toFixed(1)+'頭身'};$('brushSize').oninput=e=>$('brushOut').value=e.target.value;
document.querySelectorAll('.brush').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;document.querySelectorAll('.brush').forEach(x=>x.classList.toggle('active',x===b))});document.querySelector('[data-mode=keep]').classList.add('active');
$('downloadBtn').onclick=()=>downloadCanvas(out,'sprite_sd_128.png');$('compareBtn').onclick=()=>{const c=document.createElement('canvas');c.width=384;c.height=256;const x=c.getContext('2d');x.fillStyle='#eef1f6';x.fillRect(0,0,c.width,c.height);x.drawImage(src,0,0,256,256);x.imageSmoothingEnabled=false;x.drawImage(out,256,64,128,128);downloadCanvas(c,'sprite_sd_compare.png')};
window.SpriteStudio1190={loadBlob,run};
if(new URLSearchParams(location.search).has('selftest')){setTimeout(async()=>{let ok=false,msg='';try{const r=await fetch('sample/input_character.jpg');await loadBlob(await r.blob(),'selftest');ok=run();const px=octx.getImageData(0,0,128,128).data;let opaque=0;for(let i=3;i<px.length;i+=4)if(px[i])opaque++;ok=ok&&opaque>300;msg=`${ok?'PASS':'FAIL'} opaque=${opaque} source=${src.width}x${src.height}`;}catch(e){msg='FAIL '+e.message} $('selftest').hidden=false;$('selftest').textContent=msg;document.body.dataset.selftest=ok?'pass':'fail';},200)}
})();
